source 'https://supermarket.getchef.com'

cookbook 'apt', '~> 2.9.2'
cookbook 'git', '~> 4.3.4'
cookbook 'graphviz', '~> 0.1.1'
cookbook 'locale', '~> 1.0.2'
cookbook 'rvm', '~> 0.9.4'
cookbook 'nodejs', '~> 2.4.2'
cookbook 'nginx', '~> 2.7.6'
cookbook 'build-essential', '~> 2.2.4'
cookbook 'postgresql', '~> 3.4.20'
cookbook 'sudo', '~> 2.7.2'
cookbook 'user', '~> 0.4.2'
cookbook 'users', '~> 1.8.2'
cookbook 'ruby_build', '~> 0.8.0'
